### ISSUE TITLE
Frozen at start-up

### ISSUE THREAD

**Issue by Dejv311** [YeonV/home-assistant-addons#39]
Hi there,
I have issues starting up the new version of the addon. This is the output log (freezes every time):

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/ledfx.sh
cont-init: info: /etc/cont-init.d/ledfx.sh exited 0
cont-init: info: running /etc/cont-init.d/nginx.sh
cont-init: info: /etc/cont-init.d/nginx.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun ledfx (no readiness notification)
services-up: info: copying legacy longrun nginx (no readiness notification)
-----------------------------------------------------------
s6-rc: info: service legacy-services successfully started
[23:19:55] INFO: Starting NGinx...
LedFx backend host /api/hassio_ingress/BZtMcp_CayKveGZin6ajrO9M4STP89y4Brm2lLh6O7A/#/./
-----------------------------------------------------------
[23:19:55] INFO: Starting ledfx...
[INFO    ] ledfx.__main__                 : Unable to set priority, please run as root or sudo if you are experiencing frame rate issues
[DEBUG   ] ledfx.__main__                 : Linux : 6.1.21-v8 : 
[DEBUG   ] ledfx.__main__                 : 3.9.2 : ('default', 'Feb 28 2021 17:03:44') : CPython
[DEBUG   ] ledfx.__main__                 : Packages
[DEBUG   ] ledfx.__main__                 : Pillow : 10.1.0
[DEBUG   ] ledfx.__main__                 : aiohttp : 3.8.6
[DEBUG   ] ledfx.__main__                 : aiohttp-cors : 0.7.0
[DEBUG   ] ledfx.__main__                 : aiosignal : 1.3.1
[DEBUG   ] ledfx.__main__                 : async-timeout : 4.0.3
[DEBUG   ] ledfx.__main__                 : attrs : 23.1.0
[DEBUG   ] ledfx.__main__                 : aubio : 0.4.9
[DEBUG   ] ledfx.__main__                 : certifi : 2023.11.17
[DEBUG   ] ledfx.__main__                 : cffi : 1.16.0
[DEBUG   ] ledfx.__main__                 : charset-normalizer : 3.3.2
[DEBUG   ] ledfx.__main__                 : flux-led : 1.0.4
[DEBUG   ] ledfx.__main__                 : frozenlist : 1.4.0
[DEBUG   ] ledfx.__main__                 : icmplib : 3.0.4
[DEBUG   ] ledfx.__main__                 : idna : 3.6
[DEBUG   ] ledfx.__main__                 : ifaddr : 0.2.0
[DEBUG   ] ledfx.__main__                 : ledfx : 2.0.80
[DEBUG   ] ledfx.__main__                 : multidict : 5.0.2
[DEBUG   ] ledfx.__main__                 : numpy : 1.19.5
[DEBUG   ] ledfx.__main__                 : openrgb-python : 0.2.15
[DEBUG   ] ledfx.__main__                 : paho-mqtt : 1.6.1
[DEBUG   ] ledfx.__main__                 : pip : 20.3.4
[DEBUG   ] ledfx.__main__                 : pkgconfig : 1.5.5
[DEBUG   ] ledfx.__main__                 : psutil : 5.9.6
[DEBUG   ] ledfx.__main__                 : pycparser : 2.21
[DEBUG   ] ledfx.__main__                 : pyserial : 3.5
[DEBUG   ] ledfx.__main__                 : pystray : 0.19.5
[DEBUG   ] ledfx.__main__                 : python-osc : 1.8.3
[DEBUG   ] ledfx.__main__                 : python-rtmidi : 1.5.8
[DEBUG   ] ledfx.__main__                 : python-xlib : 0.33
[DEBUG   ] ledfx.__main__                 : requests : 2.28.2
[DEBUG   ] ledfx.__main__                 : rpi-ws281x : 5.0.0
[DEBUG   ] ledfx.__main__                 : sacn : 1.6.4
[DEBUG   ] ledfx.__main__                 : samplerate : 0.1.0
[DEBUG   ] ledfx.__main__                 : sentry-sdk : 1.14.0
[DEBUG   ] ledfx.__main__                 : setuptools : 59.4.0
[DEBUG   ] ledfx.__main__                 : six : 1.16.0
[DEBUG   ] ledfx.__main__                 : sounddevice : 0.4.6
[DEBUG   ] ledfx.__main__                 : urllib3 : 1.26.18
[DEBUG   ] ledfx.__main__                 : uvloop : 0.19.0
[DEBUG   ] ledfx.__main__                 : voluptuous : 0.12.2
[DEBUG   ] ledfx.__main__                 : webcolors : 1.13
[DEBUG   ] ledfx.__main__                 : wheel : 0.42.0
[DEBUG   ] ledfx.__main__                 : yarl : 1.9.3
[DEBUG   ] ledfx.__main__                 : zeroconf : 0.39.4
[INFO    ] ledfx.__main__                 : LedFx Core is initializing
[INFO    ] ledfx.config                   : LedFx Configuration Version: 2.2.0
[INFO    ] ledfx.core                     : Using uvloop for asyncio loop
[DEBUG   ] ledfx.utils                    : Importing ['ledfx.api.audio_devices', 'ledfx.api.bpm', 'ledfx.api.colors', 'ledfx.api.com_ports', 'ledfx.api.config', 'ledfx.api.device', 'ledfx.api.device_status', 'ledfx.api.devices', 'ledfx.api.effect', 'ledfx.api.effects', 'ledfx.api.fetch', 'ledfx.api.find_devices', 'ledfx.api.find_launchpad', 'ledfx.api.find_openrgb', 'ledfx.api.get_nanoleaf_token', 'ledfx.api.info', 'ledfx.api.integration_qlc', 'ledfx.api.integration_spotify', 'ledfx.api.integrations', 'ledfx.api.log', 'ledfx.api.notification', 'ledfx.api.ping', 'ledfx.api.presets', 'ledfx.api.scenes', 'ledfx.api.schema', 'ledfx.api.shutdown', 'ledfx.api.specified_device_status', 'ledfx.api.utils', 'ledfx.api.virtual', 'ledfx.api.virtual_effects', 'ledfx.api.virtual_presets', 'ledfx.api.virtual_tools', 'ledfx.api.virtuals', 'ledfx.api.virtuals_tools', 'ledfx.api.websocket'] from ledfx.api
[INFO    ] ledfx.core                     : Starting LedFx
[DEBUG   ] ledfx.utils                    : Importing ['ledfx.devices.adalight', 'ledfx.devices.ddp', 'ledfx.devices.e131', 'ledfx.devices.hue', 'ledfx.devices.launchpad', 'ledfx.devices.launchpad_lib', 'ledfx.devices.nanoleaf', 'ledfx.devices.open_pixel_control', 'ledfx.devices.openrgb', 'ledfx.devices.osc', 'ledfx.devices.packets', 'ledfx.devices.rpi_ws281x', 'ledfx.devices.udp', 'ledfx.devices.wled', 'ledfx.devices.zengee'] from ledfx.devices
[DEBUG   ] ledfx.utils                    : Importing ['ledfx.effects.audio', 'ledfx.effects.bands', 'ledfx.effects.bands_matrix', 'ledfx.effects.bar', 'ledfx.effects.blade_power_plus', 'ledfx.effects.block_reflections', 'ledfx.effects.blocks', 'ledfx.effects.crawler', 'ledfx.effects.droplets', 'ledfx.effects.energy', 'ledfx.effects.energy2', 'ledfx.effects.equalizer', 'ledfx.effects.fade', 'ledfx.effects.fire', 'ledfx.effects.glitch', 'ledfx.effects.gradient', 'ledfx.effects.hsv_effect', 'ledfx.effects.lava_lamp', 'ledfx.effects.magnitude', 'ledfx.effects.marching', 'ledfx.effects.math', 'ledfx.effects.mel', 'ledfx.effects.melbank', 'ledfx.effects.melt', 'ledfx.effects.melt_and_sparkle', 'ledfx.effects.metro', 'ledfx.effects.modulate', 'ledfx.effects.multiBar', 'ledfx.effects.pitchSpectrum', 'ledfx.effects.pixels', 'ledfx.effects.power', 'ledfx.effects.rain', 'ledfx.effects.rainbow', 'ledfx.effects.real_strobe', 'ledfx.effects.scan', 'ledfx.effects.scan_and_flare', 'ledfx.effects.scan_multi', 'ledfx.effects.scroll', 'ledfx.effects.singleColor', 'ledfx.effects.spectrum', 'ledfx.effects.strobe', 'ledfx.effects.temporal', 'ledfx.effects.water', 'ledfx.effects.wavelength'] from ledfx.effects
[DEBUG   ] ledfx.utils                    : Importing ['ledfx.integrations.mqtt', 'ledfx.integrations.mqtt_hass', 'ledfx.integrations.qlc', 'ledfx.integrations.spotify'] from ledfx.integrations
```

Addon settings left at default:

```
ssl: false
log_level: debug
certfile: fullchain.pem
keyfile: privkey.pem
```

I have previously used many different versions of LedFX in HA. I remember, that they kept their internal setting even when uninstalled (when migrating from "official" dead version by Frenck to the Beta version). Maybe deleting those old settings would help? But I have no idea where the internal settings of LedFX are stored. Help appreciated.

```
Home Assistant 2023.9.3
Supervisor 2023.11.6
Operating System 11.1
Frontend 20230911.0 - latest
```

**Comment by Dejv311** [comment]
Hi there, thank you for getting back to me, I tried running the dev version, but it is not able to run on "new" version of HA.

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 215, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 818, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/ledfx/__init__.py", line 31, in <module>
    from .helper import build_auth, get_config_value
  File "/config/custom_components/ledfx/helper.py", line 17, in <module>
    from .updater import LedFxUpdater
  File "/config/custom_components/ledfx/updater.py", line 21, in <module>
    from homeassistant.helpers.entity import (
ImportError: cannot import name 'DeviceEntryType' from 'homeassistant.helpers.entity' (/usr/src/homeassistant/homeassistant/helpers/entity.py)
```

May be related to issue described in:
https://github.com/jmcollin78/versatile_thermostat/issues/100

**Comment by spiro-c** [comment]
The issue you have here is from custom components integration assuming you are usig
 https://github.com/dmamontov/hass-ledfx
How much i know this is not maintained any more and is not working 
I think this one https://github.com/DeKaN/hass-ledfx is working on default installation of the dev addon you set host 127.0.0.1 port 8888

**Comment by Dejv311** [comment]
Yes, you are right, sorry for the confusion. Closing this issue. Thank you for your time.
